### ISSUE TITLE
Does this library support server-side rendering?

### ISSUE THREAD

**Issue by dverbru** [revelrylabs/react-uniqueid#1]
Hi.
I noticed internally this uses a counter to generate the IDs. Does that approach work with universal apps?
Thanks!

**Comment by karlhorky** [comment]
Would be cool to get a definitive answer on this + example if necessary.

**Comment by jwietelmann** [comment]
That was the idea, but this lib is painfully out of date and unmaintained. I'm not even actually sure it's still a good idea. If you would like to try your hand at the same concept without the lib, the key concepts here are:

* The `Provider` provides IDs through [context](https://reactjs.org/docs/context.html)
* The `connect`ed components receive this context
* The `Provider` resets its counter function in the constructor.
* So long as your `Provider` instance is constructed on each server page load, and it is constructed on each client page load, the IDs will match, and you won't get those checksum errors that force a full re-render.

**Comment by prehnRA** [comment]
Closed because it is a quite old issue and the README seems to indicate that this will work in an isomorphic app situation.
